### ISSUE TITLE
Timeouts and Colons

### ISSUE THREAD

**Issue by Bushingz** [makkoncept/yts_torrents#1]
Hi, firstly I would like to say thank you for developing this. I started to do this myself and then decided to check github for a solution. I was not disappointed. 

First issue I ran into is timeouts. I'm using a VPN so maybe this is why I saw these issues, but the timeout value of 3 seconds was not enough for me. I had issues even with 10 seconds. I upped the timeout to 30 seconds and had no issues. Although, upon a timeout, the error is unhandled.

Second issue is with colons. When downloading a torrent with a colon in the name, os.path.join saw it as a drive letter and threw away the rest of the string. Therefore you would end up with a torrent missing half of its name as well as an extension. I was able to fix this by changing line 66 in "linkdowload.py" from:
`movie = movie.encode('utf-8').decode('utf-8')`
to:
`movie = movie.encode('utf-8').decode('utf-8').replace(':','')`

Once again, thanks for creating this. Saved me a ton of time and I will continue to modify it to fit my needs.

I do not support piracy. This is for educational purposes only.

**Comment by makkoncept** [comment]
Hey @SpencerXZX, good to hear you find the script helpful. Thanks for pointing out the colons issue. Feel free to submit a PR if you find anything that will improve the script!
